import { Geist, Geist_Mono } from "next/font/google";
import { Merriweather, Rubik_Distressed } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

// Default Geist fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// New Google fonts
const merriweather = Merriweather({
  variable: "--font-merriweather",
  weight: ["300", "400", "700", "900"], // choose weights you need
  subsets: ["latin"],
});

const rubikDistressed = Rubik_Distressed({
  variable: "--font-rubik-distressed",
  weight: "400", // only one available for distressed
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${merriweather.variable} ${rubikDistressed.variable} antialiased`}
      >
        <Header />

        {children}
      </body>
    </html>
  );
}
